### ISSUE TITLE
`unknow command` Error

### ISSUE THREAD

**Issue by qtopie** [invicnaper/cmus-youtube#1]
I have installed and configured cmus by your tutorial in the readme file. But when I typed `:youtube-dl` , I got `Error: unknow command` message.
According to your setting at the `command_mode.c` file, I don't think the command should be  `youtube-dl`, it should be `youtube` instead.

**Comment by invicnaper** [comment]
Yea you're right , I just edited the Readme File to correct the command . So it's youtube instead of youtube-dl
