### ISSUE TITLE
Error: youtube-dl not installed Ubuntu 16.04

### ISSUE THREAD

**Issue by jjmonsalveg** [invicnaper/cmus-youtube#2]
I have followed the installation manual of the plugin, but when I run the command :youtube I get the message:

` Error: youtube-dl not installed, install it using apt-get install youtube-dl`

> $uname -ar
> Linux jj-VIT-P2400 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> $ cmus --version
> cmus v2.8.0-rc0-43-gc64e0d5
> Copyright 2004-2006 Timo Hirvonen
> Copyright 2008-2016 Various Authors

What can be going wrong?

**Comment by invicnaper** [comment]
Youtube-dl is not installed so try executing sudo apt-get install youtube-dl

**Comment by jjmonsalveg** [comment]
Sorry, I forgot to mention that I have it installed:

>   $ youtube-dl --version
>     2016.02.22

But that message is displayed, randomly displays the message or creates a video.mp4 file that has no content (in home user directory)
