### ISSUE TITLE
cmd_youtube undeclared here 

### ISSUE THREAD

**Issue by MAKROFREEK** [invicnaper/cmus-youtube#8]
`   cmus   git:(master) ✗ make
   CC     command_mode.o
command_mode.c:2686:74: error: 'cmd_youtube' undeclared here (not in a function)
 2686 |         { "youtube",                                                     cmd_youtube,                                    1, 1,  NULL,                                                                   0, 0          },
      |                                                                          ^~~~~~~~~~~
make: *** [scripts/lib.mk:66: command_mode.o] Error 1
   cmus   git:(master) ✗ `

- sorry in advance if i'm missing something blatantly obvious here

**Comment by MAKROFREEK** [comment]
This happens every time I run make

**Comment by vhferoli** [comment]
I have same problem
